### PR TITLE
Adding aolBidAdapter adapter

### PR DESCRIPTION
**Pull request by shlomisut**

### CODE REVIEW

**Comment by ghost** [comment]
Build Failed - please check http://jenkins.thetimmedia.site:8080/job/prebid_pull_request/106/

**Comment by shlomisut** [comment]
retest this please

**Comment by ghost** [comment]
Build Failed - please check http://jenkins.thetimmedia.site:8080/job/prebid_pull_request/107/

**Comment by ghost** [comment]
Build Failed - please check http://jenkins.thetimmedia.site:8080/job/prebid_pull_request/108/

**Comment by shlomisut** [comment]
retest this please

**Comment by ghost** [comment]
Build Passed

**Comment by shlomisut** [comment]
retest this please

**Comment by ghost** [comment]
Build Passed

**Pull request merged**
