### PR TITLE
Boris/prebid for main continue

### PR DESCRIPTION
**Pull request by borisjaskerovich**
please look at timBidAdapetr.md, timBidAdapetr_spec.js . (all file not only changes)

### CODE REVIEW

**Review by shlomisut — APPROVED** [review]

**Comment by ghost** [comment]
Build Passed

**Comment by ghost** [comment]
Build Passed

**Comment by ghost** [comment]
Build Passed

**Comment by shlomisut** [comment]
retest this please

**Comment by ghost** [comment]
Build Passed

**Comment by shlomisut** [comment]
retest this please

**Comment by ghost** [comment]
Build Failed - please check http://jenkins.thetimmedia.site:8080/job/prebid_pull_request/79/

**Comment by ghost** [comment]
Build Failed - please check http://jenkins.thetimmedia.site:8080/job/prebid_pull_request/80/

**Comment by ghost** [comment]
Build Failed - please check http://jenkins.thetimmedia.site:8080/job/prebid_pull_request/81/

**Comment by ghost** [comment]
Build Passed

**Comment by ghost** [comment]
Build Passed

**Comment by ghost** [comment]
Build Passed

**Pull request merged**
